config/routes.rb
Rails.application.routes.draw do

  root 'static_page#home'

  get 'blog/new_post' => 'post#new'

  post 'new_post' => 'post#create', :as => 'new_post'

  get 'blog/:slug' => 'post#show', :as => 'post'

  
  get '/project' => 'static_page#project'

  get '/hardware' => 'static_page#hardware'

  get '/contact' => 'static_page#contact'

  get '/login' => 'session#new'

  post '/login' => 'session#create', :as => 'log_in'

  get '/logout' => 'session#destroy', :as => 'log_out'

end

app/models/post.rb
class Post < ActiveRecord::Base
	belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :posts
	attr_accessor :password

	def self.authenticate(username, password)
		@user = User.find_by(username: username)
		if @user && @user.password_hash == BCrypt::Engine.hash_secret(password, @user.password_salt)
			@user
		else
			nil
		end
	end

	def encrypt_password(password)
		self.password_salt = BCrypt::Engine.generate_salt
		self.password_hash = BCrypt::Engine.hash_secret(password, self.password_salt)
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def raise_404
  	raise ActionController::RoutingError.new("Not Found")
  end
end

app/controllers/post_controller.rb
class PostController < ApplicationController
  def new
    if !session[:logged_in].nil? && session[:user_access_level] == 1
  	 @post = Post.new
    else
      redirect_to :root
    end
  end

  def create
  	@post = Post.new
  	@post.title = params[:post][:title]
  	@post.body = params[:post][:body]
  	@post.author = "Mark"
  	@post.slug = params[:post][:title].gsub(/[ ]/, '-').downcase
  	if @post.save
  		redirect_to post_path(@post.slug)
  	else
  		render "post/new"
  	end
  end

  def show
  	@post = Post.find_by(slug: params[:slug])
  end
end

app/controllers/session_controller.rb
class SessionController < ApplicationController
  def new
  	if session[:logged_in].nil?
  	else
  		flash[:alert] = "You are already logged in"
  		redirect_to :root
  	end
  end

  def create
  	@user = User.authenticate(params["/login"][:username], params["/login"][:password])
  	if @user
  		session[:logged_in] = true
  		session[:user_access_level] = @user.access_level
  		flash[:notice] = "Logged in"
  		redirect_to :root
  	else
  		flash.now[:alert] = "There was a problem logging you in"
  		render 'new'
  	end
  end

  def destroy
  	if !session[:logged_in].nil?
	  	session[:logged_in] = nil
	  	session[:user_access_level] = nil
	  	flash[:notice] = "Logged out"
	  	redirect_to :root
	else
		redirect_to :root
	end
  end
end

app/controllers/static_page_controller.rb
class StaticPageController < ApplicationController
  def home
  	@posts = Post.all.limit(10).order(created_at: :desc)
  end

  def project
  end

  def hardware
  end

  def contact
  end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  def new
  	if !session[:logged_in].nil?
  		@user = User.new
  	else
  		flash[:alert] = "You are already logged in"
  		redirect_to :root
  	end
  end

  def create
  	@user = User.new
  	@user.username = params["/signup"][:username]
  	@user.email = params["/signup"][:email]
  	@user.access_level = 3
  	@user.encrypt_password(params["/signup"][:password])
  	if @user.save
  		flash[:notice] = "Thanks for signing up"
  		session[:logged_in] = true
  		session[:user_access_level] = @user.access_level
  		redirect_to :root
  	else
  		flash.now[:alert] = "There was a problem signing up"
  		render new
  	end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def markdown(text)
		render_options = {
			filter_html: true,
			hard_wrap: true,
			link_attributes: { rel: 'nofollow' }
		}

		renderer = Redcarpet::Render::HTML.new(render_options)

		extensions = {
			autolink: true,
			fenced_code_blocks: true,
			lax_spacing: true,
			no_intra_emphasis: true,
			strikethrough: true,
			superscript: true
		}

		Redcarpet::Markdown.new(renderer, extensions).render(text).html_safe
	end
end

app/helpers/post_helper.rb
module PostHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/helpers/static_page_helper.rb
module StaticPageHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Rubypi</title>
  <link rel="stylesheet" href="/css/normalize.css">
  <link rel="stylesheet" href="/css/foundation.css">
  <link rel="stylesheet" href="/css/app.css">
  <%= csrf_meta_tags %>
</head>
<body>
	<nav class="top-bar" data-topbar role="navigation">
		<ul class="title-area">
			<li class="name"><h1><a href="/">RubyPi</a></h1></li>
			<li class="toggle-topbar menu-icon"><a href="#"><span>Menu</span></a></li>
		</ul>

		<section class="top-bar-section">
			<!-- right nav links -->
			<ul class="right">
				<li><a href="/">Home</a></li>
				<li><a href="/project">The Project</a></li>
				<li><a href="/hardware">The Hardware</a></li>
				<li><a href="/contact">Contact Me</a></li>
				<% if !session[:logged_in].nil? %>
					<li><a href="blog/new_post">New Post</a></li>
					<li><a href="/logout">Logout</a></li>
				<% end %>
			</ul>
		</section>
	</nav>
	<% flash.each do |key, value| %>
		<div class="large-6 large-centered columns">
			<% if key == "notice" %>
				<div data-alert class="alert-box success radius"><%= value %><a href="#" class="close">&times;</a></div>
			<% else %>
				<div data-alert class="alert-box alert radius"><%= value %><a href="#" class="close">&times;</a></div>
			<% end %>
		</div>
	<% end %>
	<div class="row">
		<div class="large-9 columns">
			<%= yield %>
		</div>
		<aside class="large-3 columns">
			<h5>Categories</h5>
			<ul class="side-nav">
				<li><a href="/#">Tutorial</a></li>
				<li><a href="/#">Rails</a></li>
				<li><a href="/#">Nginx</a></li>
				<li><a href="/#">News</a></li>
			</ul>
		</aside>
	</div>

<script src="/js/vendor/jquery.js"></script>
<script src="/js/vendor/modernizr.js"></script>
<script src="/js/foundation.min.js"></script>
<script src="/js/foundation/foundation.alert.js"></script>
<script src="/js/foundation/foundation.topbar.js"></script>
<script>
	$(document).foundation();
</script>
</body>
</html>

app/views/post/create.html.erb
<h1>Post#create</h1>
<p>Find me in app/views/post/create.html.erb</p>

app/views/post/new.html.erb
<h3>New Post</h3>
<%= form_for @post, :url => :new_post do |f| %>
	<%= f.label :title %></br>
	<%= f.text_field :title %></br>

	<%= f.label :body %></br>
	<%= f.text_area :body, :rows => 9 %></br>

	<%= f.submit :save, :class => "button small" %>
<% end %>

app/views/post/show.html.erb
<article>
	<h3><%= @post.title %></h3>
	<h6>Posted by <%= @post.author %> on <%= @post.created_at %></h6>
	<%= markdown(@post.body) %>
</article>

app/views/session/create.html.erb
<h1>Session#create</h1>
<p>Find me in app/views/session/create.html.erb</p>

app/views/session/destroy.html.erb
<h1>Session#destroy</h1>
<p>Find me in app/views/session/destroy.html.erb</p>

app/views/session/new.html.erb
<h3>Login</h3>
<%= form_for log_in_path do |f| %>
	<div class="row">
		<div class="large-12 columns">
			<%= f.label :username %>
			<%= f.text_field :username %>
		</div>

		<div class="large-12 columns">
			<%= f.label :password %>
			<%= f.password_field :password %>
		</div>

		<div class="large-12 columns">
			<%= f.submit :Login, :class => "button small" %>
		</div>
	</div>
<% end %>

app/views/static_page/contact.html.erb
<h1>StaticPage#contact</h1>
<p>Find me in app/views/static_page/contact.html.erb</p>

app/views/static_page/hardware.html.erb
<h1>StaticPage#hardware</h1>
<p>Find me in app/views/static_page/hardware.html.erb</p>

app/views/static_page/home.html.erb
<% @posts.each do |p| %>
	<article>
		<h3><a href="/blog/<%= p.slug %>"><%= p.title %></a></h3>
		<h6>Posted by <%= p.author %> on <%= p.created_at %></h6>
		<%= markdown(p.body[0, 150]) %>
	</article>
	<hr/>
<% end %>

app/views/static_page/project.html.erb
<h1>StaticPage#project</h1>
<p>Find me in app/views/static_page/project.html.erb</p>

app/views/user/create.html.erb
<h1>User#create</h1>
<p>Find me in app/views/user/create.html.erb</p>

app/views/user/new.html.erb
<h3>Signup</h3>
<%= form_for sign_up_path, :data => 'data-abide' do |f| %>
	<div class="row">
		<div class="large-12 columns">
			<%= f.label :username %>
			<%= f.text_field :username %>
		</div>
		<div class="large-12 columns">
			<%= f.label :email %>
			<%= f.email_field :email %>
		</div>
		<div class="large-12 columns">
			<%= f.label :password %>
			<%= f.password_field :password %>
		</div>
		<div class="large-12 columns">
			<%= f.submit :Signup, :class => "button small" %>
		</div>
	</div>
<% end %>